AzureWebApplication/Models/Tag.cs
using System.Collections.Generic;

namespace AzureWebApplication.Models
{
	public class Tag
	{
		public Tag()
		{
			Posts = new List<Post>();
		}
		public int Id { get; set; }
		public string Name { get; set; }
		public int Count { get; set; }
		public virtual ICollection<Post> Posts { get; set; }
	}
}

AzureWebApplication/Areas/Admin/Controllers/TagController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using AzureWebApplication.Application;
using AzureWebApplication.Areas.Admin.Models;
using AzureWebApplication.Models;

namespace AzureWebApplication.Areas.Admin.Controllers
{
	public class TagController : BaseController
	{
		public ActionResult Add(int postId)
		{
			var post = db.Posts.Find(postId);

			if (post == null)
				return HttpNotFound();

			ViewBag.tagId = new SelectList(db.Tags, "Id", "Name");

			return View();
		}

		[HttpPost]
		public ActionResult Add(int postId, AddTagViewModel model)
		{
			var post = db.Posts.Find(postId);

			if (post == null)
				return HttpNotFound();

			if (model.Tagid.HasValue)
			{
				var tag = db.Tags.Find(model.Tagid.Value);
				if (tag == null)
					return HttpNotFound();

				post.Tags.Add(tag);
				db.SaveChanges();
			}
			else
			{
				db.Tags.Add(new Tag
				{
					Name = model.TagName,
					Posts = new List<Post> {post}
				});
			}

			db.SaveChanges();

			return RedirectToAction("Index", "Post");
		}

		public ActionResult Recalc()
		{
			var tags = db.Tags.Include(x => x.Posts);
			foreach (var tag in tags)
			{
				tag.Count = tag.Posts.Count(x => x.Published);
			}
			db.SaveChanges();
			return RedirectToAction("Index", "Post");
		}

		public ActionResult Manage(int postId)
		{
			var post = db.Posts.Find(postId);
			if (post == null)
				return HttpNotFound();
			return View(post);
		}

		public ActionResult Delete(int postId, int tagId)
		{
			var tag = db.Tags.Find(tagId);
			var post = db.Posts.Find(postId);
			if (tag == null || post == null)
				return HttpNotFound();

			post.Tags.Remove(tag);
			db.SaveChanges();

			return RedirectToAction("Manage", postId);
		}
	}
}

AzureWebApplication/Areas/Admin/Views/Tag/Add.cshtml
@model AzureWebApplication.Areas.Admin.Models.AddTagViewModel

@{
    ViewBag.Title = "Add";
}

<h2>Добавить тэг</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
             @Html.LabelFor(model => model.Tagid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Tagid, null, optionLabel: "Выберите", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TagName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-success" />
            </div>
        </div>
    </div>
}

AzureWebApplication/Areas/Admin/Views/Tag/Manage.cshtml
@model AzureWebApplication.Models.Post
@{
    ViewBag.Title = "Тэги для поста";
}

<h2 class="page-header">@ViewBag.Title</h2>@Html.ActionLink("Добавить тэг", "Add", "Tag", new { postId = Model.Id }, new { @class = "btn btn-default btn-sm" })
<div class="row">
    <div class="col-md-12">

        <table class="table table-striped">
            <tbody>
            @foreach (var item in Model.Tags)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@Html.ActionLink("Удалить", "Delete", "Tag", new {postId = Model.Id, tagId = item.Id}, new {@class = "btn btn-danger"})</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>