AzureWebApplication/Areas/Admin/Controllers/PostController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AzureWebApplication.Application;
using AzureWebApplication.Models;

namespace AzureWebApplication.Areas.Admin.Controllers
{
	[Authorize]
	public class PostController : BaseController
	{
		// GET: Admin/Post
		public ActionResult Index()
		{
			return View(db.Posts.Include(x => x.Tags).OrderByDescending(x => x.CreateTime).Take(20));
		}

		public ActionResult Publish(int id)
		{
			db.Posts.Find(id).Published = true;
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult UnPublish(int id)
		{
			db.Posts.Find(id).Published = false;
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		// GET: Admin/Post/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Admin/Post/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "Title,Content")] Post post)
		{
			post.CreateTime = DateTime.Now;
			if (ModelState.IsValid)
			{
				db.Posts.Add(post);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(post);
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			var post = db.Posts.Find(id);
			if (post == null)
			{
				return HttpNotFound();
			}
			return View(post);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, [Bind(Include = "Title,Content")] Post model)
		{
			var originalTag = db.Posts.Find(id);
			if (originalTag == null)
				return HttpNotFound();
			originalTag.Title = model.Title;
			originalTag.Content = model.Content;

			if (ModelState.IsValid)
			{
				db.Entry(originalTag).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(model);
		}

		// GET: Admin/Post/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var post = db.Posts.Find(id);
			if (post == null)
			{
				return HttpNotFound();
			}
			return View(post);
		}

		// POST: Admin/Post/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			var post = db.Posts.Find(id);
			db.Posts.Remove(post);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

AzureWebApplication/Controllers/OptionController.cs
using System.Web.Mvc;
using AzureWebApplication.Application;

namespace AzureWebApplication.Controllers
{
	public class OptionController : BaseController
	{
		[ChildActionOnly]
		public ActionResult Value(string key)
		{
			return new ContentResult {Content = db.Options.Find(key).Value};
		}
	}
}

AzureWebApplication/Views/Shared/Layout.cshtml
@using System.Configuration
@{
    Layout = "Super.cshtml";
}

@section TopMenu
{
    <li>@Html.ActionLink("Обо мне", "About", "Home")</li>
    <li>@Html.ActionLink("Для потенциальных работодателей", "Cv", "Home")</li>
    @if (ConfigurationManager.AppSettings["dev"] != null || User.Identity.IsAuthenticated)
    {
        <li>
            <a href="@Url.Action("Index", "Post", new {area = "Admin"})">Админка</a>
        </li>
    }
}

<div class="row">
    <div class="col-md-9">
        @RenderBody()
    </div>
    <div class="col-md-3">
        @Html.Action("TagList", "Home")
    </div>
</div>

AzureWebApplication/Views/Shared/Super.cshtml
@using System.Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@ViewBag.Description">
    <title>@ViewBag.Title - @Html.Action("Value", "Option", new { key = "blog-name", area = "" })</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    @Styles.Render("~/bundles/css")
</head>
<body>

    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Главная", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @RenderSection("TopMenu")
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Html.Action("Value", "Option", new { key = "blog-name", area = "" })</p>
        </footer>
    </div>

    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", false)
</body>
</html>